### ISSUE TITLE
 could not load library:  "C:\Users\USER\.julia\artifacts\~~~\bin\cudnn64_7.dll"

### ISSUE THREAD

**Issue by nuclear718** [JuliaGPU/CUDAapi.jl#111]
The CUDA tool kit and cudnn were installed done! (The ENV variable was setting done!)

But the Fllux initialized or test(CUDAdrv, CUDAnative, CuArrays) are still can not found cudnn64_7.dll

```
using CUDAdrv, CUDAnative, CuArrays
Pkg.test(["CUDAdrv", "CUDAnative", "CuArrays"])

[ Info: Testing using device GeForce GTX 1650 SUPER (compute capability 7.5.0, 3.233 GiB available memory) on CUDA driver 11.0.0 and toolkit 10.2.89
multi dim, sliced setindex: Error During Test at C:\Users\USER\.julia\packages\GPUArrays\QDGmr\test\testsuite\indexing.jl:51
  Got exception outside of a @test
  could not load library "C:\Users\USER\.julia\artifacts\d0bdf3cb548b47e0ea9808e88a130b8e4a924257\bin\cudnn64_7.dll"
  The specified module could not be found.
```

  **Stacktrace:**

```
[1] #dlopen#3(::Bool, ::typeof(Libdl.dlopen), ::String, ::UInt32) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Libdl\src\Libdl.jl:109
   [2] dlopen at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Libdl\src\Libdl.jl:109 [inlined] (repeats 2 times)
   [3] use_artifact_cudnn(::VersionNumber) at C:\Users\USER\.julia\packages\CuArrays\e8PLr\src\bindeps.jl:187
   [4] use_artifact_cuda() at C:\Users\USER\.julia\packages\CuArrays\e8PLr\src\bindeps.jl:131
   [5] __configure_dependencies__(::Bool) at C:\Users\USER\.julia\packages\CuArrays\e8PLr\src\bindeps.jl:235
   [6] __configure__(::Bool) at C:\Users\USER\.julia\packages\CuArrays\e8PLr\src\CuArrays.jl:117
   [7] (::CuArrays.var"#1#2"{Bool})() at C:\Users\USER\.julia\packages\CuArrays\e8PLr\src\CuArrays.jl:45
   [8] lock(::CuArrays.var"#1#2"{Bool}, ::ReentrantLock) at .\lock.jl:151
   [9] _functional(::Bool) at C:\Users\USER\.julia\packages\CuArrays\e8PLr\src\CuArrays.jl:43
   [10] functional at C:\Users\USER\.julia\packages\CuArrays\e8PLr\src\CuArrays.jl:36 [inlined]
   [11] macro expansion at C:\Users\USER\.julia\packages\CuArrays\e8PLr\src\CuArrays.jl:63 [inlined]
   [12] libcurand at C:\Users\USER\.julia\packages\CuArrays\e8PLr\src\bindeps.jl:37 [inlined]
   [13] (::CuArrays.CURAND.var"#13122#cache_fptr!#11")() at C:\Users\USER\.julia\packages\CUDAapi\XuSHC\src\call.jl:31
   [14] curandCreateGenerator(::Base.RefValue{Ptr{Nothing}}, ::CuArrays.CURAND.curandRngType) at C:\Users\USER\.julia\packages\CUDAapi\XuSHC\src\call.jl:39
   [15] CuArrays.CURAND.RNG(::CuArrays.CURAND.curandRngType) at C:\Users\USER\.julia\packages\CuArrays\e8PLr\src\rand\random.jl:23
   [16] RNG at C:\Users\USER\.julia\packages\CuArrays\e8PLr\src\rand\random.jl:22 [inlined]
   [17] #123 at C:\Users\USER\.julia\packages\CuArrays\e8PLr\src\rand\CURAND.jl:34 [inlined]
   [18] get!(::CuArrays.CURAND.var"#123#124", ::IdDict{Any,Any}, ::Any) at .\abstractdict.jl:661
   [19] generator() at C:\Users\USER\.julia\packages\CuArrays\e8PLr\src\rand\CURAND.jl:33
   [20] rand!(::CuArray{Float32,4,Nothing}) at C:\Users\USER\.julia\packages\CuArrays\e8PLr\src\rand\random.jl:166
   [21] macro expansion at C:\Users\USER\.julia\packages\GPUArrays\QDGmr\test\testsuite\indexing.jl:54 [inlined]
   [22] macro expansion at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107 [inlined]
   [23] macro expansion at C:\Users\USER\.julia\packages\GPUArrays\QDGmr\test\testsuite\indexing.jl:52 [inlined]
   [24] macro expansion at C:\Users\USER\.julia\packages\GPUArrays\QDGmr\src\host\indexing.jl:63 [inlined]
   [25] macro expansion at C:\Users\USER\.julia\packages\GPUArrays\QDGmr\test\testsuite\indexing.jl:41 [inlined]
   [26] macro expansion at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107 [inlined]
   [27] test_indexing(::Type) at C:\Users\USER\.julia\packages\GPUArrays\QDGmr\test\testsuite\indexing.jl:3
   [28] test(::Type{CuArray}) at C:\Users\USER\.julia\packages\GPUArrays\QDGmr\test\testsuite.jl:51
   [29] top-level scope at C:\Users\USER\.julia\packages\CuArrays\e8PLr\test\runtests.jl:49
   [30] top-level scope at 
.
.
.
.
.
.

copyto! for triangular: Error During Test at C:\Users\USER\.julia\packages\GPUArrays\QDGmr\test\testsuite\linalg.jl:14
  Got exception outside of a @test
  could not load library "C:\Users\USER\.julia\artifacts\d0bdf3cb548b47e0ea9808e88a130b8e4a924257\bin\cudnn64_7.dll"
  The specified module could not be found.
  
  Stacktrace:
   [1] #dlopen#3(::Bool, ::typeof(Libdl.dlopen), ::String, ::UInt32) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Libdl\src\Libdl.jl:109
   [2] dlopen at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Libdl\src\Libdl.jl:109 [inlined] (repeats 2 times)
   [3] use_artifact_cudnn(::VersionNumber) at C:\Users\USER\.julia\packages\CuArrays\e8PLr\src\bindeps.jl:187
   [4] use_artifact_cuda() at C:\Users\USER\.julia\packages\CuArrays\e8PLr\src\bindeps.jl:131
   [5] __configure_dependencies__(::Bool) at C:\Users\USER\.julia\packages\CuArrays\e8PLr\src\bindeps.jl:235
   [6] __configure__(::Bool) at C:\Users\USER\.julia\packages\CuArrays\e8PLr\src\CuArrays.jl:117
   [7] (::CuArrays.var"#1#2"{Bool})() at 
Float32 gemm C := adjoint(A) * transpose(B) * a + C * b: Error During Test at C:\Users\USER\.julia\packages\GPUArrays\QDGmr\test\testsuite\linalg.jl:83
  Test threw exception
  Expression: compare(mul!, AT, C, f(A), g(B), Ref(T(4)), Ref(T(5)))
  could not load library "C:\Users\USER\.julia\artifacts\d0bdf3cb548b47e0ea9808e88a130b8e4a924257\bin\cudnn64_7.dll"
  The specified module could not be found.
```

My Pkg.status():

```
 [fbb218c0] BSON v0.2.5
  [336ed68f] CSV v0.6.0
  [c5f51814] CUDAdrv v6.2.2
  [be33ccc6] CUDAnative v3.0.4
  [3a865a2d] CuArrays v2.0.1
  [1b08a953] Dash v0.1.0 #master (https://github.com/plotly/Dash.jl.git)
  [a93c6f00] DataFrames v0.20.2
  [1313f7d8] DataFramesMeta v0.5.0
  [587475ba] Flux v0.10.4
  [38e38edf] GLM v1.3.9
  [cd3eb016] HTTP v0.8.13
  [09f84164] HypothesisTests v0.9.2
  [7073ff75] IJulia v1.21.1
  [add582a8] MLJ v0.10.3
  [91a5bcdd] Plots v0.29.9
```

My versioninfo():

```
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: AMD Ryzen 5 3600X 6-Core Processor             
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, znver1)
```

**Comment by maleadt** [comment]
> The CUDA tool kit and cudnn were installed done! (The ENV variable was setting done!)

I'm not sure what you mean by this.

Also, please use triple backticks to format code output.

**Comment by nuclear718** [comment]
The problem was solved, I copy the file "cudnn64_7.dll" into 
"C:\Users\USER\.julia\artifacts\d0bdf3cb548b47e0ea9808e88a130b8e4a924257\bin\"
After copy the file into the artifacts folder manually, everything is normal without error.

The root cause is still unknown!
